In [1]:
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
#from sklearn.ensemble import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
import numpy as np
import string
import csv
import sys

#### RFC
from sklearn.model_selection import train_test_split
from sklearn.cross_validation import KFold
#from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

C:\Users\Sohrab-PC\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
kdd_info = pd.read_csv('Original.csv')

In [3]:
kdd_info.head()
kdd_info.count()

province        3262
city            3262
city_code       3262
station         3262
station_code    3262
aqi             2657
so2_24h         2929
no2_24h         2929
co_24h          2929
o3_24h          2909
o3_8h_24h       2909
pm2_5_24h       2929
pm10_24h        2929
pubtime         3262
dtype: int64

In [4]:
kdd_info.describe()

,city_code,station_code,aqi,so2_24h,no2_24h,co_24h,o3_24h,o3_8h_24h,pm2_5_24h,pm10_24h,pubtime
count,3262.0,3262.000000,2657.000000,2929.000000,2929.000000,2929.000000,2909.000000,2909.000000,2929.000000,2929.000000,3262.000000
mean,140100.0,1085.021153,87.702296,65.141004,42.379993,1.461304,93.973874,77.340323,62.843974,117.454763,42550.908645
std,0.0,2.579110,48.511168,73.739968,22.691550,0.860172,52.512336,44.937987,53.403633,77.080604,104.941176
min,140100.0,1081.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,42370.000000
25%,140100.0,1083.000000,56.000000,19.000000,27.000000,0.854000,53.000000,41.000000,28.000000,64.000000,42460.000000
50%,140100.0,1085.000000,78.000000,36.000000,39.000000,1.236000,85.000000,73.000000,48.000000,101.000000,42551.000000
75%,140100.0,1087.000000,106.000000,81.000000,54.000000,1.841000,128.000000,106.000000,77.000000,148.000000,42641.000000
max,140100.0,1089.000000,361.000000,582.000000,141.000000,5.513000,303.000000,232.000000,414.000000,541.000000,42735.000000

In [5]:
kdd_info.shape
#train.drop('aqi',axis=1, inplace=True)
#kdd_info.drop('pubtime', axis=1, inplace=True)
#kdd_info.drop('city_code', axis=1, inplace=True)
#kdd_info.drop('station_code', axis=1, inplace=True)
kdd_info.drop('station', axis=1, inplace=True)
kdd_info.drop('city', axis=1, inplace=True)
kdd_info.drop('province', axis=1, inplace=True)
kdd_info.drop('o3_8h_24h', axis=1, inplace=True)
kdd_info.count()

city_code       3262
station_code    3262
aqi             2657
so2_24h         2929
no2_24h         2929
co_24h          2929
o3_24h          2909
pm2_5_24h       2929
pm10_24h        2929
pubtime         3262
dtype: int64

In [6]:
imputed_DF = kdd_info
imputed_DF = imputed_DF.dropna()
'''
from sklearn.preprocessing import Imputer

imp = Imputer(missing_values='NaN', strategy='mean', axis=1)
#imputed_DF = pd.DataFrame(imp.fit_transform(kdd_info))
imputed_DF['aqi'] = pd.DataFrame(imp.fit_transform(imputed_DF['aqi']).ravel())
imputed_DF['so2_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['so2_24h']).ravel())
imputed_DF['no2_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['no2_24h']).ravel())
imputed_DF['co_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['co_24h']).ravel())
imputed_DF['o3_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['o3_24h']).ravel())
imputed_DF['pm2_5_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['pm2_5_24h']).ravel())
imputed_DF['pm10_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['pm10_24h']).ravel())

#Converting float pubtime to DateTime format
#imputed_DF['pubtime'] = pd.to_datetime(imputed_DF['pubtime'], format='%m/%d/%Y')
#imputed_DF['pubtime'] = imputed_DF['pubtime'].dt.total_seconds()

imputed_DF.columns = kdd_info.columns
imputed_DF.index = kdd_info.index
imputed_DF.count()
imputed_DF.count()

#kdd_info.describe()
'''

"\nfrom sklearn.preprocessing import Imputer\n\nimp = Imputer(missing_values='NaN', strategy='mean', axis=1)\n#imputed_DF = pd.DataFrame(imp.fit_transform(kdd_info))\nimputed_DF['aqi'] = pd.DataFrame(imp.fit_transform(imputed_DF['aqi']).ravel())\nimputed_DF['so2_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['so2_24h']).ravel())\nimputed_DF['no2_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['no2_24h']).ravel())\nimputed_DF['co_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['co_24h']).ravel())\nimputed_DF['o3_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['o3_24h']).ravel())\nimputed_DF['pm2_5_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['pm2_5_24h']).ravel())\nimputed_DF['pm10_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['pm10_24h']).ravel())\n\n#Converting float pubtime to DateTime format\n#imputed_DF['pubtime'] = pd.to_datetime(imputed_DF['pubtime'], format='%m/%d/%Y')\n#imputed_DF['pubtime'] = imputed_DF['pubtime'].dt.total_seconds()\n\nimputed_DF.columns = kdd_info.columns\nimputed_DF.index = kdd_info.index\nimputed_DF.count()\nimputed_DF.count()\n\n#kdd_info.describe()\n"

In [7]:
imputed_DF.count()

city_code       2637
station_code    2637
aqi             2637
so2_24h         2637
no2_24h         2637
co_24h          2637
o3_24h          2637
pm2_5_24h       2637
pm10_24h        2637
pubtime         2637
dtype: int64

In [8]:
#train, test = train_test_split(imputed_DF, test_size = 0.2)

train, test = train_test_split(imputed_DF, test_size = 0.3, random_state = 5)

train.to_csv('new1_train_data.csv')
test.to_csv('new_test_data.csv')

In [9]:
train.shape

(1845, 10)

In [10]:
train = train.dropna()
train.shape

(1845, 10)

In [11]:
train.head(5)

,city_code,station_code,aqi,so2_24h,no2_24h,co_24h,o3_24h,pm2_5_24h,pm10_24h,pubtime
506,140100,1086,43.0,63.0,43.0,1.494,73.0,25.0,45.0,42429
2108,140100,1083,38.0,8.0,14.0,0.426,122.0,21.0,39.0,42604
2362,140100,1085,45.0,27.0,33.0,0.839,85.0,13.0,46.0,42632
807,140100,1087,96.0,92.0,25.0,1.369,107.0,36.0,141.0,42459
112,140100,1081,110.0,98.0,41.0,1.910,13.0,80.0,126.0,42389

In [12]:
train.columns

Index(['city_code', 'station_code', 'aqi', 'so2_24h', 'no2_24h', 'co_24h',
       'o3_24h', 'pm2_5_24h', 'pm10_24h', 'pubtime'],
      dtype='object')

In [13]:
# creating response vector to train our model
#response_vector=pd.DataFrame(np.array(train['aqi']),columns=['aqi'])
response_vector=pd.DataFrame(train['aqi'],columns=['aqi'])
response_vector.loc[response_vector['aqi']==1]
response_vector.head(30)
response_vector.count()

aqi    1845
dtype: int64

In [14]:
test_df1=pd.read_csv('new_test_data.csv')
test_df1.describe()

,Unnamed: 0,city_code,station_code,aqi,so2_24h,no2_24h,co_24h,o3_24h,pm2_5_24h,pm10_24h,pubtime
count,792.000000,792.0,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000
mean,1501.347222,140100.0,1085.306818,89.262626,54.948232,40.628788,1.371402,98.843434,55.704545,111.125000,42536.340909
std,860.814726,0.0,2.556676,48.679781,59.970398,20.991927,0.773315,50.239258,41.399153,69.809879,95.700016
min,0.000000,140100.0,1081.000000,17.000000,3.000000,3.000000,0.196000,1.000000,3.000000,7.000000,42370.000000
25%,749.750000,140100.0,1083.000000,58.000000,18.000000,26.000000,0.844500,60.000000,28.000000,64.000000,42453.000000
50%,1516.500000,140100.0,1085.000000,79.000000,33.000000,38.000000,1.185500,90.000000,46.000000,97.000000,42538.000000
75%,2260.750000,140100.0,1087.000000,108.000000,69.000000,51.000000,1.649750,134.000000,69.000000,141.250000,42621.000000
max,2958.000000,140100.0,1089.000000,361.000000,430.000000,141.000000,4.623000,248.000000,309.000000,541.000000,42699.000000

In [15]:
#train.drop('aqi',axis=1, inplace=True)
train.shape

(1845, 10)

In [16]:
train.head(5)

,city_code,station_code,aqi,so2_24h,no2_24h,co_24h,o3_24h,pm2_5_24h,pm10_24h,pubtime
506,140100,1086,43.0,63.0,43.0,1.494,73.0,25.0,45.0,42429
2108,140100,1083,38.0,8.0,14.0,0.426,122.0,21.0,39.0,42604
2362,140100,1085,45.0,27.0,33.0,0.839,85.0,13.0,46.0,42632
807,140100,1087,96.0,92.0,25.0,1.369,107.0,36.0,141.0,42459
112,140100,1081,110.0,98.0,41.0,1.910,13.0,80.0,126.0,42389

In [17]:
test.columns

Index(['city_code', 'station_code', 'aqi', 'so2_24h', 'no2_24h', 'co_24h',
       'o3_24h', 'pm2_5_24h', 'pm10_24h', 'pubtime'],
      dtype='object')

In [18]:
test.drop('aqi',axis=1, inplace=True)
test.shape

C:\Users\Sohrab-PC\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

(792, 9)

In [19]:
# Generic function for making a classification model and accessing the performance.
def classification_model(model, data, predictors, outcome):
    # Fit the model:
    model.fit(data[predictors], data[outcome])

    # Make predictions on training set:
    predictions = model.predict(data[predictors])

    # Perform k-fold cross-validation with 5 folds
    kf = KFold(data.shape[0], n_folds=5)
    error = []
    for train, test in kf:
        # Filter training data
        train_predictors = (data[predictors].iloc[train, :])

        # The target we're using to train the algorithm.
        train_target = data[outcome].iloc[train]

        # Training the algorithm using the predictors and target.
        model.fit(train_predictors, train_target)

        # Record error from each cross-validation run
        error.append(model.score(data[predictors].iloc[test, :], data[outcome].iloc[test]))

        print("Cross-Validation Score : %s" % "{0:.3%}".format(np.mean(error)))

    # Fit the model again so that it can be refered outside the function:
    model.fit(data[predictors], data[outcome])

In [20]:
#from sklearn.tree import DecisionTreeRegressor
#rfc=DecisionTreeRegressor()

model = RandomForestClassifier(n_estimators=100,min_samples_split=25)
print ("Random Forest: Using all relevant features(Training data)")

Random Forest: Using all relevant features(Training data)

In [21]:
#features_mean = list(imputed_DF.columns[0:13])
#print(features_mean)
#outcome_var='aqi'
#predictor_var = features_mean
#classification_model(model, response_vector.values.ravel(),predictor_var,outcome_var)

In [22]:
#rfc.fit(train,response_vector.values.ravel())
#rfc.fit(train,response_vector)
from sklearn import utils
Y_train = np.asarray(train['aqi'], dtype="|S8")
print(utils.multiclass.type_of_target(Y_train))
print(utils.multiclass.type_of_target(train.aqi))
train.drop('aqi',axis=1, inplace=True)
print(Y_train)
print(train)
model.fit(train,Y_train)

# Make predictions on training set:
#predictions = model.predict(test)

multiclass
multiclass
[b'43.0' b'38.0' b'45.0' ..., b'114.0' b'59.0' b'51.0']
      city_code  station_code  so2_24h  no2_24h  co_24h  o3_24h  pm2_5_24h  \
506      140100          1086     63.0     43.0   1.494    73.0       25.0
2108     140100          1083      8.0     14.0   0.426   122.0       21.0
2362     140100          1085     27.0     33.0   0.839    85.0       13.0
807      140100          1087     92.0     25.0   1.369   107.0       36.0
112      140100          1081     98.0     41.0   1.910    13.0       80.0
2841     140100          1087    231.0     80.0   1.846    41.0       96.0
1930     140100          1085     10.0     25.0   0.938   141.0       36.0
1192     140100          1085     37.0     25.0   0.990   132.0       44.0
2225     140100          1083     14.0     21.0   0.412   118.0       19.0
2330     140100          1089     44.0     67.0   0.767   183.0       57.0
1238     140100          1086     40.0     58.0   0.718   154.0       47.0
579      140100          1085     61.0     28.0   1.963    56.0       55.0
484      140100          1084     63.0     27.0   0.854    86.0       32.0
1507     140100          1085     39.0     41.0   0.616   140.0       25.0
2650     140100          1085     25.0     43.0   1.224    15.0       36.0
115      140100          1081     22.0      8.0   1.006    56.0       11.0
2430     140100          1081     23.0     42.0   1.029    79.0       38.0
2148     140100          1087     21.0     31.0   0.675    93.0       13.0
354      140100          1081     47.0     32.0   1.929    54.0      106.0
1609     140100          1088     30.0     57.0   1.157   166.0       71.0
2196     140100          1081     24.0     42.0   0.583    83.0       17.0
2444     140100          1086     22.0     33.0   1.122    83.0       17.0
227      140100          1085     43.0     30.0   2.366    28.0       51.0
104      140100          1081     30.0     30.0   1.287    32.0       30.0
765      140100          1081     32.0     28.0   0.725    66.0       24.0
382      140100          1083    131.0     29.0   1.714    38.0       44.0
691      140100          1088    124.0     64.0   2.666   127.0      111.0
2724     140100          1087    120.0     51.0   0.921    51.0       46.0
2660     140100          1086      8.0     37.0   0.957    18.0       24.0
828      140100          1081     17.0     19.0   0.850    71.0       21.0
...         ...           ...      ...      ...     ...     ...        ...
863      140100          1089     80.0     74.0   2.361   147.0       56.0
2905     140100          1088     42.0     49.0   2.117    64.0       67.0
1926     140100          1081     20.0     27.0   0.920   119.0       56.0
1010     140100          1083     15.0     13.0   0.375    89.0       25.0
2247     140100          1087     29.0     55.0   1.217    57.0       22.0
2307     140100          1084     35.0     56.0   0.829   123.0       27.0
1093     140100          1085     52.0     32.0   0.532   152.0       42.0
103      140100          1081     20.0     27.0   1.230    36.0       30.0
2537     140100          1089     38.0     59.0   0.642   104.0       26.0
2158     140100          1088     13.0     35.0   1.246   116.0       17.0
1651     140100          1085     16.0     17.0   1.243   175.0       40.0
41       140100          1088     47.0     41.0   2.131    57.0       32.0
1556     140100          1089     24.0     46.0   1.190   205.0       30.0
423      140100          1085    103.0     30.0   2.630    61.0       68.0
1435     140100          1085     46.0     41.0   1.989   198.0       68.0
2465     140100          1089     76.0     93.0   2.133   236.0      158.0
2252     140100          1083     13.0     18.0   0.383    70.0       12.0
233      140100          1085     14.0     13.0   0.891    49.0       11.0
1199     140100          1083     24.0     17.0   0.715   114.0       25.0
2331     140100          1081     44.0     45.0   1.458   165.0       81.0
1641     140100          1084      9.0     33.0   0.832   152.0       39.0
232      140100          1085    163.0     43.0   2.681    45.0       92.0
2763     140100          1081    202.0    108.0   3.475    40.0      235.0
2227     140100          1085     28.0     39.0   1.042   123.0       35.0
830      140100          1083     11.0     10.0   0.502    74.0       14.0
1158     140100          1087     75.0     20.0   0.884   139.0       41.0
2383     140100          1088     34.0     50.0   1.950   117.0       89.0
1599     140100          1087     57.0     45.0   1.396   188.0       57.0
1938     140100          1084     13.0     24.0   0.650   121.0       38.0
2533     140100          1085     29.0     60.0   1.267    87.0       30.0

      pm10_24h  pubtime
506       45.0    42429
2108      39.0    42604
2362      46.0    42632
807      141.0    42459
112      126.0    42389
2841     330.0    42685
1930      53.0    42584
1192     118.0    42502
2225      42.0    42617
2330     194.0    42628
1238     120.0    42507
579      186.0    42433
484       52.0    42429
1507      72.0    42537
2650      52.0    42664
115       41.0    42392
2430      72.0    42640
2148      64.0    42608
354      137.0    42411
1609     171.0    42548
2196      46.0    42614
2444      47.0    42641
227       87.0    42380
104       64.0    42381
765       84.0    42455
382       59.0    42403
691      235.0    42446
2724     159.0    42672
2660      36.0    42665
828      128.0    42462
...        ...      ...
863      102.0    42465
2905     147.0    42693
1926      81.0    42584
1010      98.0    42482
2247      96.0    42619
2307      60.0    42626
1093     138.0    42491
103       76.0    42380
2537      85.0    42651
2158      53.0    42609
1651      65.0    42553
41        66.0    42380
1556      74.0    42542
423       98.0    42408
1435     108.0    42529
2465     309.0    42643
2252      27.0    42620
233       39.0    42386
1199      45.0    42503
2331     148.0    42629
1641      61.0    42552
232      148.0    42385
2763     467.0    42677
2227      78.0    42617
830       63.0    42462
1158      86.0    42498
2383     167.0    42634
1599     176.0    42547
1938      65.0    42585
2533      54.0    42651

[1845 rows x 9 columns]

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=25, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [23]:
predictions = model.predict(test)
#predictionsArray = np.asarray(predictions, dtype="|S6")
#np.asarray(predictionsArray, dtype=np.float64) is predictionsArray
print(predictions)
print(test_df1.aqi)

[b'66.0' b'64.0' b'146.0' b'61.0' b'91.0' b'66.0' b'78.0' b'43.0' b'116.0'
 b'27.0' b'50.0' b'60.0' b'124.0' b'64.0' b'79.0' b'64.0' b'49.0' b'144.0'
 b'102.0' b'22.0' b'103.0' b'22.0' b'77.0' b'151.0' b'175.0' b'51.0'
 b'174.0' b'55.0' b'82.0' b'152.0' b'93.0' b'75.0' b'56.0' b'82.0' b'103.0'
 b'103.0' b'61.0' b'66.0' b'27.0' b'118.0' b'95.0' b'91.0' b'202.0'
 b'126.0' b'102.0' b'91.0' b'60.0' b'37.0' b'43.0' b'175.0' b'43.0' b'72.0'
 b'75.0' b'83.0' b'101.0' b'46.0' b'61.0' b'61.0' b'106.0' b'88.0' b'116.0'
 b'96.0' b'56.0' b'66.0' b'75.0' b'88.0' b'47.0' b'128.0' b'85.0' b'95.0'
 b'133.0' b'103.0' b'68.0' b'103.0' b'30.0' b'45.0' b'50.0' b'27.0' b'66.0'
 b'94.0' b'91.0' b'43.0' b'175.0' b'86.0' b'42.0' b'76.0' b'85.0' b'159.0'
 b'127.0' b'60.0' b'61.0' b'175.0' b'126.0' b'160.0' b'91.0' b'161.0'
 b'111.0' b'84.0' b'66.0' b'94.0' b'101.0' b'126.0' b'97.0' b'41.0'
 b'111.0' b'99.0' b'41.0' b'50.0' b'83.0' b'32.0' b'91.0' b'43.0' b'56.0'
 b'124.0' b'76.0' b'67.0' b'22.0' b'50.0' b'78.0' b'27.0' b'60.0' b'67.0'
 b'71.0' b'116.0' b'72.0' b'49.0' b'59.0' b'106.0' b'22.0' b'54.0' b'91.0'
 b'233.0' b'41.0' b'58.0' b'80.0' b'53.0' b'124.0' b'60.0' b'58.0' b'88.0'
 b'53.0' b'111.0' b'75.0' b'96.0' b'61.0' b'46.0' b'27.0' b'34.0' b'51.0'
 b'66.0' b'93.0' b'61.0' b'60.0' b'60.0' b'79.0' b'70.0' b'83.0' b'151.0'
 b'124.0' b'88.0' b'74.0' b'124.0' b'45.0' b'64.0' b'77.0' b'288.0'
 b'219.0' b'75.0' b'64.0' b'78.0' b'43.0' b'50.0' b'140.0' b'79.0' b'128.0'
 b'82.0' b'85.0' b'45.0' b'102.0' b'121.0' b'70.0' b'41.0' b'124.0' b'91.0'
 b'55.0' b'56.0' b'66.0' b'127.0' b'82.0' b'87.0' b'95.0' b'79.0' b'116.0'
 b'133.0' b'61.0' b'75.0' b'53.0' b'50.0' b'110.0' b'58.0' b'95.0' b'91.0'
 b'95.0' b'41.0' b'102.0' b'219.0' b'67.0' b'202.0' b'116.0' b'91.0'
 b'75.0' b'56.0' b'61.0' b'51.0' b'132.0' b'56.0' b'41.0' b'75.0' b'109.0'
 b'140.0' b'91.0' b'98.0' b'76.0' b'43.0' b'50.0' b'91.0' b'88.0' b'91.0'
 b'66.0' b'127.0' b'61.0' b'71.0' b'79.0' b'219.0' b'88.0' b'63.0' b'35.0'
 b'75.0' b'72.0' b'63.0' b'60.0' b'60.0' b'140.0' b'46.0' b'85.0' b'105.0'
 b'219.0' b'71.0' b'41.0' b'50.0' b'53.0' b'71.0' b'51.0' b'116.0' b'110.0'
 b'205.0' b'94.0' b'73.0' b'77.0' b'38.0' b'61.0' b'219.0' b'51.0' b'56.0'
 b'32.0' b'185.0' b'84.0' b'50.0' b'75.0' b'88.0' b'103.0' b'88.0' b'50.0'
 b'51.0' b'27.0' b'58.0' b'71.0' b'61.0' b'58.0' b'75.0' b'61.0' b'54.0'
 b'85.0' b'167.0' b'140.0' b'94.0' b'56.0' b'43.0' b'102.0' b'100.0'
 b'91.0' b'64.0' b'22.0' b'60.0' b'106.0' b'132.0' b'50.0' b'24.0' b'79.0'
 b'97.0' b'37.0' b'274.0' b'102.0' b'274.0' b'109.0' b'110.0' b'109.0'
 b'129.0' b'99.0' b'56.0' b'42.0' b'77.0' b'34.0' b'66.0' b'69.0' b'159.0'
 b'33.0' b'175.0' b'126.0' b'124.0' b'101.0' b'80.0' b'43.0' b'158.0'
 b'82.0' b'185.0' b'219.0' b'46.0' b'111.0' b'51.0' b'121.0' b'70.0'
 b'79.0' b'185.0' b'94.0' b'121.0' b'88.0' b'161.0' b'109.0' b'27.0'
 b'80.0' b'88.0' b'94.0' b'78.0' b'75.0' b'102.0' b'132.0' b'109.0' b'79.0'
 b'53.0' b'78.0' b'124.0' b'29.0' b'60.0' b'45.0' b'102.0' b'93.0' b'27.0'
 b'160.0' b'41.0' b'78.0' b'45.0' b'76.0' b'128.0' b'75.0' b'87.0' b'116.0'
 b'66.0' b'67.0' b'69.0' b'84.0' b'58.0' b'91.0' b'52.0' b'22.0' b'124.0'
 b'126.0' b'66.0' b'79.0' b'37.0' b'80.0' b'19.0' b'43.0' b'46.0' b'91.0'
 b'119.0' b'77.0' b'170.0' b'55.0' b'175.0' b'119.0' b'55.0' b'53.0'
 b'137.0' b'99.0' b'102.0' b'30.0' b'100.0' b'116.0' b'100.0' b'85.0'
 b'67.0' b'82.0' b'136.0' b'110.0' b'124.0' b'126.0' b'68.0' b'106.0'
 b'91.0' b'79.0' b'56.0' b'71.0' b'105.0' b'38.0' b'118.0' b'94.0' b'146.0'
 b'88.0' b'66.0' b'34.0' b'88.0' b'124.0' b'63.0' b'51.0' b'110.0' b'60.0'
 b'175.0' b'88.0' b'43.0' b'78.0' b'88.0' b'105.0' b'66.0' b'58.0' b'219.0'
 b'100.0' b'43.0' b'116.0' b'66.0' b'85.0' b'64.0' b'132.0' b'46.0'
 b'132.0' b'95.0' b'124.0' b'77.0' b'77.0' b'81.0' b'102.0' b'288.0'
 b'66.0' b'44.0' b'88.0' b'91.0' b'100.0' b'61.0' b'72.0' b'61.0' b'117.0'
 b'29.0' b'92.0' b'66.0' b'96.0' b'102.0' b'130.0' b'78.0' b'111.0' b'91.0'
 b'119.0' b'66.0' b'56.0' b'83.0' b'103.0' b'75.0' b'53.0' b'46.0' b'46.0'
 b'219.0' b'67.0' b'121.0' b'219.0' b'53.0' b'77.0' b'56.0' b'66.0'
 b'109.0' b'71.0' b'56.0' b'79.0' b'159.0' b'85.0' b'27.0' b'38.0' b'65.0'
 b'85.0' b'82.0' b'66.0' b'105.0' b'66.0' b'85.0' b'55.0' b'75.0' b'99.0'
 b'37.0' b'73.0' b'91.0' b'62.0' b'105.0' b'105.0' b'27.0' b'109.0'
 b'103.0' b'63.0' b'111.0' b'185.0' b'96.0' b'202.0' b'59.0' b'84.0'
 b'85.0' b'91.0' b'106.0' b'91.0' b'46.0' b'214.0' b'75.0' b'66.0' b'102.0'
 b'84.0' b'132.0' b'27.0' b'41.0' b'132.0' b'22.0' b'75.0' b'66.0' b'70.0'
 b'88.0' b'288.0' b'56.0' b'58.0' b'61.0' b'214.0' b'22.0' b'64.0' b'38.0'
 b'92.0' b'51.0' b'99.0' b'43.0' b'50.0' b'67.0' b'56.0' b'75.0' b'175.0'
 b'71.0' b'22.0' b'50.0' b'110.0' b'71.0' b'109.0' b'95.0' b'45.0' b'30.0'
 b'51.0' b'77.0' b'24.0' b'32.0' b'77.0' b'78.0' b'94.0' b'96.0' b'34.0'
 b'95.0' b'77.0' b'63.0' b'54.0' b'83.0' b'78.0' b'49.0' b'34.0' b'43.0'
 b'80.0' b'88.0' b'53.0' b'159.0' b'36.0' b'101.0' b'71.0' b'68.0' b'132.0'
 b'159.0' b'109.0' b'95.0' b'117.0' b'24.0' b'159.0' b'85.0' b'43.0'
 b'214.0' b'175.0' b'103.0' b'91.0' b'95.0' b'109.0' b'43.0' b'61.0'
 b'91.0' b'175.0' b'75.0' b'32.0' b'94.0' b'32.0' b'175.0' b'74.0' b'103.0'
 b'151.0' b'116.0' b'83.0' b'56.0' b'61.0' b'40.0' b'72.0' b'51.0' b'118.0'
 b'46.0' b'90.0' b'53.0' b'61.0' b'32.0' b'101.0' b'288.0' b'60.0' b'94.0'
 b'61.0' b'46.0' b'75.0' b'61.0' b'46.0' b'43.0' b'61.0' b'140.0' b'32.0'
 b'91.0' b'124.0' b'50.0' b'50.0' b'75.0' b'45.0' b'42.0' b'56.0' b'69.0'
 b'175.0' b'88.0' b'105.0' b'124.0' b'82.0' b'58.0' b'61.0' b'69.0' b'24.0'
 b'58.0' b'36.0' b'77.0' b'105.0' b'100.0' b'146.0' b'106.0' b'47.0'
 b'110.0' b'110.0' b'123.0' b'53.0' b'88.0' b'109.0' b'46.0' b'86.0'
 b'159.0' b'76.0' b'67.0' b'77.0' b'121.0' b'71.0' b'85.0' b'22.0' b'100.0'
 b'56.0' b'136.0' b'46.0' b'36.0' b'144.0' b'56.0' b'103.0' b'110.0'
 b'70.0' b'43.0' b'47.0' b'71.0' b'79.0' b'128.0' b'102.0' b'82.0' b'175.0'
 b'102.0' b'106.0' b'87.0' b'103.0' b'75.0' b'38.0' b'175.0' b'53.0'
 b'34.0' b'212.0' b'73.0' b'124.0' b'175.0' b'53.0' b'117.0' b'63.0'
 b'79.0' b'110.0' b'55.0' b'45.0' b'105.0' b'51.0' b'61.0' b'124.0' b'79.0'
 b'73.0' b'78.0' b'85.0' b'75.0' b'54.0' b'66.0' b'95.0' b'71.0' b'95.0'
 b'91.0' b'100.0' b'61.0' b'95.0' b'29.0' b'100.0' b'172.0' b'111.0'
 b'38.0' b'159.0' b'87.0' b'71.0' b'288.0' b'288.0' b'54.0' b'121.0'
 b'33.0' b'144.0' b'50.0' b'64.0' b'83.0' b'109.0' b'96.0' b'51.0' b'127.0'
 b'144.0' b'99.0' b'135.0' b'219.0' b'93.0' b'185.0' b'120.0' b'103.0'
 b'56.0' b'102.0' b'136.0' b'75.0' b'95.0' b'88.0' b'36.0' b'105.0' b'66.0'
 b'63.0' b'106.0' b'91.0' b'56.0' b'82.0' b'75.0' b'219.0' b'38.0' b'30.0'
 b'90.0' b'75.0']
0       66.0
1       62.0
2      151.0
3       62.0
4       87.0
5       65.0
6       79.0
7       41.0
8      113.0
9       25.0
10      50.0
11      59.0
12     140.0
13      56.0
14      73.0
15      64.0
16      48.0
17     134.0
18     100.0
19      27.0
20     102.0
21      25.0
22      74.0
23     148.0
24     207.0
25      55.0
26     195.0
27      51.0
28      82.0
29     153.0
       ...
762     54.0
763    130.0
764    133.0
765     96.0
766    150.0
767    260.0
768     95.0
769    178.0
770    121.0
771    104.0
772     51.0
773    102.0
774    143.0
775     76.0
776     92.0
777     89.0
778     34.0
779    112.0
780     71.0
781     60.0
782    107.0
783     87.0
784     55.0
785     81.0
786     71.0
787    155.0
788     38.0
789     26.0
790     90.0
791     89.0
Name: aqi, Length: 792, dtype: float64

In [24]:
newarray = np.asarray(test_df1['aqi'], dtype="|S8")
print(newarray)

[b'66.0' b'62.0' b'151.0' b'62.0' b'87.0' b'65.0' b'79.0' b'41.0' b'113.0'
 b'25.0' b'50.0' b'59.0' b'140.0' b'56.0' b'73.0' b'64.0' b'48.0' b'134.0'
 b'100.0' b'27.0' b'102.0' b'25.0' b'74.0' b'148.0' b'207.0' b'55.0'
 b'195.0' b'51.0' b'82.0' b'153.0' b'96.0' b'71.0' b'56.0' b'80.0' b'101.0'
 b'99.0' b'61.0' b'73.0' b'27.0' b'116.0' b'91.0' b'90.0' b'235.0' b'125.0'
 b'106.0' b'92.0' b'62.0' b'36.0' b'46.0' b'171.0' b'40.0' b'70.0' b'81.0'
 b'85.0' b'94.0' b'45.0' b'61.0' b'60.0' b'108.0' b'88.0' b'116.0' b'95.0'
 b'53.0' b'70.0' b'73.0' b'87.0' b'47.0' b'130.0' b'81.0' b'97.0' b'140.0'
 b'110.0' b'68.0' b'98.0' b'23.0' b'46.0' b'48.0' b'27.0' b'69.0' b'92.0'
 b'85.0' b'42.0' b'179.0' b'86.0' b'44.0' b'71.0' b'85.0' b'174.0' b'124.0'
 b'59.0' b'66.0' b'170.0' b'120.0' b'163.0' b'115.0' b'163.0' b'111.0'
 b'78.0' b'67.0' b'92.0' b'96.0' b'126.0' b'96.0' b'40.0' b'112.0' b'99.0'
 b'47.0' b'58.0' b'87.0' b'26.0' b'91.0' b'45.0' b'56.0' b'122.0' b'78.0'
 b'69.0' b'21.0' b'48.0' b'71.0' b'29.0' b'60.0' b'67.0' b'71.0' b'118.0'
 b'70.0' b'49.0' b'63.0' b'107.0' b'28.0' b'54.0' b'98.0' b'199.0' b'42.0'
 b'58.0' b'81.0' b'55.0' b'144.0' b'60.0' b'65.0' b'92.0' b'53.0' b'133.0'
 b'74.0' b'97.0' b'64.0' b'46.0' b'30.0' b'34.0' b'50.0' b'66.0' b'99.0'
 b'63.0' b'60.0' b'59.0' b'85.0' b'70.0' b'77.0' b'160.0' b'123.0' b'87.0'
 b'74.0' b'128.0' b'47.0' b'63.0' b'77.0' b'308.0' b'332.0' b'74.0' b'64.0'
 b'90.0' b'36.0' b'45.0' b'136.0' b'75.0' b'120.0' b'81.0' b'86.0' b'43.0'
 b'100.0' b'155.0' b'73.0' b'37.0' b'180.0' b'87.0' b'55.0' b'58.0' b'66.0'
 b'132.0' b'79.0' b'83.0' b'95.0' b'89.0' b'118.0' b'165.0' b'65.0' b'71.0'
 b'56.0' b'52.0' b'115.0' b'57.0' b'94.0' b'88.0' b'95.0' b'42.0' b'103.0'
 b'236.0' b'66.0' b'193.0' b'125.0' b'87.0' b'82.0' b'56.0' b'63.0' b'53.0'
 b'125.0' b'55.0' b'38.0' b'76.0' b'113.0' b'150.0' b'85.0' b'140.0'
 b'76.0' b'44.0' b'47.0' b'77.0' b'94.0' b'96.0' b'66.0' b'128.0' b'62.0'
 b'69.0' b'76.0' b'216.0' b'86.0' b'63.0' b'35.0' b'73.0' b'75.0' b'63.0'
 b'58.0' b'60.0' b'144.0' b'50.0' b'86.0' b'106.0' b'273.0' b'69.0' b'41.0'
 b'52.0' b'51.0' b'69.0' b'49.0' b'118.0' b'104.0' b'203.0' b'95.0' b'74.0'
 b'76.0' b'39.0' b'64.0' b'212.0' b'52.0' b'59.0' b'31.0' b'182.0' b'83.0'
 b'47.0' b'75.0' b'83.0' b'109.0' b'85.0' b'52.0' b'54.0' b'26.0' b'62.0'
 b'65.0' b'52.0' b'59.0' b'74.0' b'57.0' b'52.0' b'86.0' b'163.0' b'139.0'
 b'95.0' b'60.0' b'43.0' b'106.0' b'124.0' b'91.0' b'65.0' b'17.0' b'58.0'
 b'117.0' b'136.0' b'46.0' b'21.0' b'86.0' b'94.0' b'41.0' b'283.0'
 b'101.0' b'293.0' b'115.0' b'118.0' b'113.0' b'133.0' b'134.0' b'58.0'
 b'45.0' b'83.0' b'33.0' b'69.0' b'73.0' b'185.0' b'33.0' b'157.0' b'125.0'
 b'127.0' b'97.0' b'79.0' b'41.0' b'165.0' b'81.0' b'185.0' b'224.0'
 b'40.0' b'115.0' b'52.0' b'160.0' b'79.0' b'69.0' b'180.0' b'93.0'
 b'120.0' b'101.0' b'166.0' b'122.0' b'29.0' b'81.0' b'85.0' b'95.0'
 b'78.0' b'81.0' b'116.0' b'126.0' b'118.0' b'78.0' b'56.0' b'79.0'
 b'151.0' b'31.0' b'60.0' b'47.0' b'94.0' b'96.0' b'28.0' b'169.0' b'42.0'
 b'78.0' b'42.0' b'74.0' b'122.0' b'77.0' b'85.0' b'143.0' b'62.0' b'69.0'
 b'70.0' b'81.0' b'62.0' b'90.0' b'48.0' b'25.0' b'211.0' b'134.0' b'65.0'
 b'80.0' b'38.0' b'79.0' b'24.0' b'48.0' b'43.0' b'88.0' b'135.0' b'80.0'
 b'164.0' b'57.0' b'173.0' b'118.0' b'57.0' b'53.0' b'163.0' b'98.0'
 b'98.0' b'30.0' b'109.0' b'131.0' b'100.0' b'85.0' b'69.0' b'79.0'
 b'139.0' b'112.0' b'120.0' b'121.0' b'76.0' b'110.0' b'92.0' b'88.0'
 b'55.0' b'67.0' b'112.0' b'37.0' b'112.0' b'98.0' b'149.0' b'86.0' b'79.0'
 b'36.0' b'112.0' b'122.0' b'64.0' b'53.0' b'122.0' b'61.0' b'211.0'
 b'97.0' b'43.0' b'71.0' b'83.0' b'104.0' b'68.0' b'58.0' b'187.0' b'95.0'
 b'43.0' b'115.0' b'67.0' b'81.0' b'63.0' b'130.0' b'51.0' b'128.0' b'92.0'
 b'119.0' b'76.0' b'70.0' b'84.0' b'103.0' b'361.0' b'66.0' b'45.0' b'92.0'
 b'85.0' b'99.0' b'64.0' b'74.0' b'58.0' b'108.0' b'27.0' b'94.0' b'66.0'
 b'96.0' b'97.0' b'159.0' b'79.0' b'129.0' b'83.0' b'117.0' b'75.0' b'56.0'
 b'93.0' b'114.0' b'74.0' b'56.0' b'47.0' b'45.0' b'313.0' b'63.0' b'155.0'
 b'252.0' b'55.0' b'79.0' b'56.0' b'69.0' b'120.0' b'70.0' b'57.0' b'85.0'
 b'160.0' b'83.0' b'28.0' b'38.0' b'64.0' b'98.0' b'87.0' b'72.0' b'115.0'
 b'67.0' b'83.0' b'54.0' b'68.0' b'101.0' b'38.0' b'72.0' b'86.0' b'61.0'
 b'101.0' b'99.0' b'32.0' b'118.0' b'108.0' b'62.0' b'112.0' b'180.0'
 b'94.0' b'194.0' b'59.0' b'85.0' b'85.0' b'84.0' b'110.0' b'89.0' b'47.0'
 b'253.0' b'74.0' b'67.0' b'99.0' b'81.0' b'124.0' b'28.0' b'38.0' b'129.0'
 b'21.0' b'73.0' b'66.0' b'78.0' b'89.0' b'316.0' b'58.0' b'63.0' b'60.0'
 b'218.0' b'25.0' b'62.0' b'38.0' b'93.0' b'51.0' b'100.0' b'43.0' b'51.0'
 b'78.0' b'37.0' b'82.0' b'181.0' b'72.0' b'23.0' b'47.0' b'104.0' b'65.0'
 b'112.0' b'91.0' b'48.0' b'23.0' b'51.0' b'76.0' b'20.0' b'26.0' b'76.0'
 b'76.0' b'100.0' b'95.0' b'30.0' b'100.0' b'74.0' b'68.0' b'60.0' b'83.0'
 b'72.0' b'47.0' b'32.0' b'41.0' b'89.0' b'88.0' b'52.0' b'152.0' b'36.0'
 b'100.0' b'72.0' b'71.0' b'121.0' b'149.0' b'116.0' b'102.0' b'111.0'
 b'19.0' b'169.0' b'91.0' b'40.0' b'192.0' b'163.0' b'102.0' b'93.0'
 b'98.0' b'116.0' b'42.0' b'70.0' b'91.0' b'164.0' b'75.0' b'32.0' b'90.0'
 b'29.0' b'161.0' b'71.0' b'101.0' b'145.0' b'117.0' b'84.0' b'59.0'
 b'62.0' b'49.0' b'72.0' b'54.0' b'118.0' b'44.0' b'89.0' b'59.0' b'61.0'
 b'26.0' b'97.0' b'309.0' b'61.0' b'91.0' b'63.0' b'49.0' b'75.0' b'60.0'
 b'47.0' b'40.0' b'58.0' b'140.0' b'33.0' b'94.0' b'134.0' b'46.0' b'47.0'
 b'75.0' b'46.0' b'45.0' b'58.0' b'69.0' b'171.0' b'86.0' b'100.0' b'132.0'
 b'80.0' b'59.0' b'59.0' b'68.0' b'27.0' b'56.0' b'35.0' b'76.0' b'106.0'
 b'100.0' b'149.0' b'106.0' b'53.0' b'106.0' b'108.0' b'127.0' b'50.0'
 b'90.0' b'108.0' b'41.0' b'85.0' b'151.0' b'84.0' b'71.0' b'75.0' b'119.0'
 b'75.0' b'85.0' b'26.0' b'100.0' b'55.0' b'147.0' b'44.0' b'30.0' b'167.0'
 b'57.0' b'110.0' b'111.0' b'73.0' b'44.0' b'46.0' b'78.0' b'76.0' b'129.0'
 b'101.0' b'83.0' b'201.0' b'102.0' b'113.0' b'81.0' b'100.0' b'78.0'
 b'42.0' b'170.0' b'54.0' b'35.0' b'203.0' b'73.0' b'120.0' b'203.0'
 b'51.0' b'122.0' b'64.0' b'74.0' b'111.0' b'60.0' b'46.0' b'99.0' b'50.0'
 b'63.0' b'134.0' b'78.0' b'73.0' b'77.0' b'84.0' b'73.0' b'54.0' b'63.0'
 b'93.0' b'71.0' b'97.0' b'89.0' b'98.0' b'66.0' b'93.0' b'26.0' b'104.0'
 b'187.0' b'119.0' b'39.0' b'153.0' b'87.0' b'69.0' b'286.0' b'324.0'
 b'55.0' b'107.0' b'32.0' b'145.0' b'46.0' b'51.0' b'79.0' b'108.0'
 b'101.0' b'54.0' b'130.0' b'133.0' b'96.0' b'150.0' b'260.0' b'95.0'
 b'178.0' b'121.0' b'104.0' b'51.0' b'102.0' b'143.0' b'76.0' b'92.0'
 b'89.0' b'34.0' b'112.0' b'71.0' b'60.0' b'107.0' b'87.0' b'55.0' b'81.0'
 b'71.0' b'155.0' b'38.0' b'26.0' b'90.0' b'89.0']

In [25]:
# Print accuracy
accuracy = metrics.accuracy_score(predictions, newarray,  normalize=True)
print("Accuracy over Testing Data: %s" % "{0:.3%}".format(accuracy))

Accuracy over Testing Data: 12.879%

In [26]:
#predict_rfc =rfc.predict(test)
from sklearn.metrics import f1_score
f1_score(newarray, predictions, average='micro')

0.12878787878787878

In [27]:
c=0
import math
predictionsArr = np.asarray(predictions, dtype="|f8")
realArr = np.asarray(newarray, dtype="|f8")

for x in range(0,len(predictionsArr)):
    c += math.fabs((predictionsArr[x]-realArr[x]))
print(100 - c/len(predictions))
c=0
for x in range(0,len(predictionsArr)):
    c += (math.fabs((predictionsArr[x]-realArr[x]))/realArr[x])*100
print(100 - c/len(predictions))

94.9419191919192
94.8904193309