In [1]:
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
#from sklearn.ensemble import DecisionTreeRegressor
#from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
import numpy as np
import string
import csv
import sys

#### RFC
from sklearn.model_selection import train_test_split
from sklearn.cross_validation import KFold
#from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

C:\Users\Sohrab-PC\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
kdd_info = pd.read_csv('Shanxi-station_day-Taiyuan.csv')

In [3]:
kdd_info.head()
kdd_info.count()

province        2904
city            2904
city_code       2904
station         2904
station code    2904
aqi             2904
so2_24h         2904
no2_24h         2904
co_24h          2904
o3_24h          2904
o3_8h_24h       2904
pm2_5_24h       2904
pm10_24h        2904
Weekday         2904
Month           2904
Date            2904
Year            2904
dtype: int64

In [4]:
kdd_info.describe()

,city_code,station code,aqi,so2_24h,no2_24h,co_24h,o3_24h,o3_8h_24h,pm2_5_24h,pm10_24h,Weekday,Month,Date,Year
count,2904.0,2904.000000,2904.000000,2904.00000,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000,2904.000000,2904.0
mean,140100.0,1085.375000,87.681939,65.59022,42.662879,1.470663,94.056474,77.408402,63.299242,118.204545,0.716253,6.476584,15.694215,2016.0
std,0.0,2.497303,46.183062,73.84401,22.496120,0.854661,52.518660,44.942860,53.357615,76.709725,0.450893,3.441775,8.812833,0.0
min,140100.0,1081.000000,17.000000,2.00000,2.000000,0.137000,1.000000,1.000000,3.000000,7.000000,0.000000,1.000000,1.000000,2016.0
25%,140100.0,1083.750000,58.000000,19.00000,27.000000,0.862000,53.000000,41.000000,29.000000,64.000000,0.000000,3.000000,8.000000,2016.0
50%,140100.0,1085.500000,79.720000,37.00000,39.000000,1.242000,85.000000,73.000000,48.000000,102.000000,1.000000,6.000000,16.000000,2016.0
75%,140100.0,1087.250000,103.000000,82.00000,55.000000,1.848000,128.000000,107.000000,78.000000,149.000000,1.000000,9.000000,23.000000,2016.0
max,140100.0,1089.000000,361.000000,582.00000,141.000000,5.513000,303.000000,232.000000,414.000000,541.000000,1.000000,12.000000,31.000000,2016.0

In [5]:
kdd_info.shape
#train.drop('aqi',axis=1, inplace=True)
#kdd_info.drop('pubtime', axis=1, inplace=True)
#kdd_info.drop('city_code', axis=1, inplace=True)
#kdd_info.drop('station_code', axis=1, inplace=True)
kdd_info.drop('station', axis=1, inplace=True)
kdd_info.drop('city', axis=1, inplace=True)
kdd_info.drop('province', axis=1, inplace=True)
kdd_info.drop('o3_8h_24h', axis=1, inplace=True)
kdd_info.count()

city_code       2904
station code    2904
aqi             2904
so2_24h         2904
no2_24h         2904
co_24h          2904
o3_24h          2904
pm2_5_24h       2904
pm10_24h        2904
Weekday         2904
Month           2904
Date            2904
Year            2904
dtype: int64

In [6]:
imputed_DF = kdd_info
'''
from sklearn.preprocessing import Imputer

imp = Imputer(missing_values='NaN', strategy='mean', axis=1)
#imputed_DF = pd.DataFrame(imp.fit_transform(kdd_info))
imputed_DF['aqi'] = pd.DataFrame(imp.fit_transform(imputed_DF['aqi']).ravel())
imputed_DF['so2_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['so2_24h']).ravel())
imputed_DF['no2_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['no2_24h']).ravel())
imputed_DF['co_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['co_24h']).ravel())
imputed_DF['o3_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['o3_24h']).ravel())
imputed_DF['pm2_5_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['pm2_5_24h']).ravel())
imputed_DF['pm10_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['pm10_24h']).ravel())

#Converting float pubtime to DateTime format
#imputed_DF['pubtime'] = pd.to_datetime(imputed_DF['pubtime'], format='%m/%d/%Y')
#imputed_DF['pubtime'] = imputed_DF['pubtime'].dt.total_seconds()

imputed_DF.columns = kdd_info.columns
imputed_DF.index = kdd_info.index
imputed_DF.count()
imputed_DF.count()

#kdd_info.describe()
'''

"\nfrom sklearn.preprocessing import Imputer\n\nimp = Imputer(missing_values='NaN', strategy='mean', axis=1)\n#imputed_DF = pd.DataFrame(imp.fit_transform(kdd_info))\nimputed_DF['aqi'] = pd.DataFrame(imp.fit_transform(imputed_DF['aqi']).ravel())\nimputed_DF['so2_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['so2_24h']).ravel())\nimputed_DF['no2_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['no2_24h']).ravel())\nimputed_DF['co_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['co_24h']).ravel())\nimputed_DF['o3_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['o3_24h']).ravel())\nimputed_DF['pm2_5_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['pm2_5_24h']).ravel())\nimputed_DF['pm10_24h'] = pd.DataFrame(imp.fit_transform(imputed_DF['pm10_24h']).ravel())\n\n#Converting float pubtime to DateTime format\n#imputed_DF['pubtime'] = pd.to_datetime(imputed_DF['pubtime'], format='%m/%d/%Y')\n#imputed_DF['pubtime'] = imputed_DF['pubtime'].dt.total_seconds()\n\nimputed_DF.columns = kdd_info.columns\nimputed_DF.index = kdd_info.index\nimputed_DF.count()\nimputed_DF.count()\n\n#kdd_info.describe()\n"

In [7]:
#train, test = train_test_split(imputed_DF, test_size = 0.2)

train, test = train_test_split(imputed_DF, test_size = 0.3, random_state = 5)

train.to_csv('new1_train_data.csv')
test.to_csv('new_test_data.csv')

In [8]:
train.shape

(2032, 13)

In [9]:
train = train.dropna()
train.shape

(2032, 13)

In [10]:
train.head(5)

,city_code,station code,aqi,so2_24h,no2_24h,co_24h,o3_24h,pm2_5_24h,pm10_24h,Weekday,Month,Date,Year
2673,140100,1083,54.9,267,97,2.887,21,221,274,0,12,3,2016
747,140100,1085,47.0,21,20,0.956,54,24,52,0,4,3,2016
1033,140100,1083,73.0,30,18,0.789,93,49,81,1,5,9,2016
1705,140100,1083,54.0,12,14,0.525,92,35,57,1,8,1,2016
1408,140100,1081,43.0,7,45,0.472,104,15,44,0,6,25,2016

In [11]:
train.columns

Index(['city_code', 'station code', 'aqi', 'so2_24h', 'no2_24h', 'co_24h',
       'o3_24h', 'pm2_5_24h', 'pm10_24h', 'Weekday', 'Month', 'Date', 'Year'],
      dtype='object')

In [12]:
# creating response vector to train our model
#response_vector=pd.DataFrame(np.array(train['aqi']),columns=['aqi'])
response_vector=pd.DataFrame(train['aqi'],columns=['aqi'])
response_vector.loc[response_vector['aqi']==1]
response_vector.head(30)
response_vector.count()

aqi    2032
dtype: int64

In [13]:
test_df1=pd.read_csv('new_test_data.csv')
test_df1.describe()

,Unnamed: 0,city_code,station code,aqi,so2_24h,no2_24h,co_24h,o3_24h,pm2_5_24h,pm10_24h,Weekday,Month,Date,Year
count,872.000000,872.0,872.000000,872.000000,872.000000,872.000000,872.000000,872.000000,872.000000,872.000000,872.000000,872.000000,872.000000,872.0
mean,1441.555046,140100.0,1085.373853,86.487741,64.802752,42.598624,1.465023,93.543578,62.876147,116.276376,0.739679,6.420872,16.044725,2016.0
std,839.015147,0.0,2.477945,47.509507,72.751674,22.398477,0.852951,51.577885,53.725379,77.589579,0.439062,3.449578,8.696388,0.0
min,0.000000,140100.0,1081.000000,17.000000,2.000000,3.000000,0.204000,1.000000,3.000000,7.000000,0.000000,1.000000,1.000000,2016.0
25%,696.500000,140100.0,1084.000000,55.000000,19.000000,27.000000,0.858500,54.000000,27.000000,62.000000,0.000000,3.000000,9.000000,2016.0
50%,1441.500000,140100.0,1085.000000,78.000000,36.000000,39.000000,1.244000,85.500000,48.000000,100.000000,1.000000,6.000000,16.000000,2016.0
75%,2135.250000,140100.0,1087.000000,103.250000,81.000000,54.250000,1.812250,126.000000,80.000000,149.000000,1.000000,9.000000,23.250000,2016.0
max,2903.000000,140100.0,1089.000000,358.000000,488.000000,126.000000,5.513000,273.000000,381.000000,476.000000,1.000000,12.000000,31.000000,2016.0

In [14]:
#train.drop('aqi',axis=1, inplace=True)
train.shape

(2032, 13)

In [15]:
train.head(5)

,city_code,station code,aqi,so2_24h,no2_24h,co_24h,o3_24h,pm2_5_24h,pm10_24h,Weekday,Month,Date,Year
2673,140100,1083,54.9,267,97,2.887,21,221,274,0,12,3,2016
747,140100,1085,47.0,21,20,0.956,54,24,52,0,4,3,2016
1033,140100,1083,73.0,30,18,0.789,93,49,81,1,5,9,2016
1705,140100,1083,54.0,12,14,0.525,92,35,57,1,8,1,2016
1408,140100,1081,43.0,7,45,0.472,104,15,44,0,6,25,2016

In [16]:
test.columns

Index(['city_code', 'station code', 'aqi', 'so2_24h', 'no2_24h', 'co_24h',
       'o3_24h', 'pm2_5_24h', 'pm10_24h', 'Weekday', 'Month', 'Date', 'Year'],
      dtype='object')

In [17]:
test.drop('aqi',axis=1, inplace=True)
test.shape

C:\Users\Sohrab-PC\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

(872, 12)

In [18]:
# Generic function for making a classification model and accessing the performance.
def classification_model(model, data, predictors, outcome):
    # Fit the model:
    model.fit(data[predictors], data[outcome])

    # Make predictions on training set:
    predictions = model.predict(data[predictors])

    # Perform k-fold cross-validation with 5 folds
    kf = KFold(data.shape[0], n_folds=5)
    error = []
    for train, test in kf:
        # Filter training data
        train_predictors = (data[predictors].iloc[train, :])

        # The target we're using to train the algorithm.
        train_target = data[outcome].iloc[train]

        # Training the algorithm using the predictors and target.
        model.fit(train_predictors, train_target)

        # Record error from each cross-validation run
        error.append(model.score(data[predictors].iloc[test, :], data[outcome].iloc[test]))

        print("Cross-Validation Score : %s" % "{0:.3%}".format(np.mean(error)))

    # Fit the model again so that it can be refered outside the function:
    model.fit(data[predictors], data[outcome])

In [19]:
#from sklearn.tree import DecisionTreeRegressor
#rfc=DecisionTreeRegressor()

model = RandomForestClassifier(n_estimators=100,min_samples_split=25)
print ("Random Forest: Using all relevant features(Training data)")

Random Forest: Using all relevant features(Training data)

In [20]:
#features_mean = list(imputed_DF.columns[0:13])
#print(features_mean)
#outcome_var='aqi'
#predictor_var = features_mean
#classification_model(model, response_vector.values.ravel(),predictor_var,outcome_var)

In [21]:
#rfc.fit(train,response_vector.values.ravel())
#rfc.fit(train,response_vector)
from sklearn import utils
Y_train = np.asarray(train['aqi'], dtype="|S8")
print(utils.multiclass.type_of_target(Y_train))
print(utils.multiclass.type_of_target(train.aqi))
train.drop('aqi',axis=1, inplace=True)
print(Y_train)
print(train)
model.fit(train,Y_train)

# Make predictions on training set:
#predictions = model.predict(test)

multiclass
continuous
[b'54.9' b'47.0' b'73.0' ..., b'87.0' b'56.0' b'62.0']
      city_code  station code  so2_24h  no2_24h  co_24h  o3_24h  pm2_5_24h  \
2673     140100          1083      267       97   2.887      21        221
747      140100          1085       21       20   0.956      54         24
1033     140100          1083       30       18   0.789      93         49
1705     140100          1083       12       14   0.525      92         35
1408     140100          1081        7       45   0.472     104         15
666      140100          1084       66       33   1.208      41         68
2625     140100          1083      282       82   2.500      12        124
633      140100          1083       37       23   1.374      76        163
1709     140100          1087       10       37   0.854     144         34
2489     140100          1083       13       24   0.892      46         43
2314     140100          1084       22       47   0.860      77         28
856      140100          1081       17       23   0.398      77         14
1458     140100          1084        9       33   0.832     152         39
2517     140100          1087      123       49   1.287      56         68
166      140100          1084       80       40   1.455      21         45
1176     140100          1081       74       32   0.845      81         53
1443     140100          1085       36       36   1.416     172         96
2294     140100          1088       39       61   2.038     116        100
2235     140100          1085       22       67   1.604      56         79
2174     140100          1088       20       43   1.117      84         29
2592     140100          1081       30       37   1.300      43         99
1173     140100          1087       64       41   1.079      97         30
976      140100          1081        7        7   0.196      76         32
433      140100          1085       99       31   1.670      45         33
1902     140100          1088        9       17   0.604      96         24
825      140100          1083       21       12   0.455      82         20
2476     140100          1086      111      107   2.579      32        184
1517     140100          1087        6       32   1.365     118         42
120      140100          1081       95       45   2.306      22         68
70       140100          1089      349       81   2.305      32         81
...         ...           ...      ...      ...     ...     ...        ...
900      140100          1086       14       34   0.497      89         64
2000     140100          1081       31       43   0.875     114         20
2816     140100          1086       63       49   2.104      55        135
2053     140100          1087       34       51   1.142     114         29
974      140100          1088       43       50   1.992     196         53
103      140100          1081       20       27   1.230      36         30
2258     140100          1084       44       41   1.204      48         46
1921     140100          1083        8       14   0.183      71          8
1470     140100          1088       12       18   1.494     146         40
41       140100          1088       47       41   2.131      57         32
1386     140100          1084       13       38   1.640     183         39
377      140100          1085       67       46   3.303      40        106
1278     140100          1088       18       38   1.092     186         50
2194     140100          1084       50       59   1.854     146         88
2004     140100          1086       22       42   0.687     143         18
205      140100          1085      153       47   2.134      13         84
1068     140100          1086       36       42   0.711     100         37
2075     140100          1085       38       51   1.737     110         98
1461     140100          1087       15       43   1.249     170         32
204      140100          1085      129       34   1.555      41         45
2718     140100          1088       82       54   1.646      60         84
2672     140100          1081      355      111   4.383      14        294
2459     140100          1085      339       92   3.404      60        214
1982     140100          1088       30       48   0.779     189         32
740      140100          1086       12       20   0.508      68         23
1032     140100          1081       61       30   1.035      99         95
2121     140100          1083       34       19   1.057     116        106
1424     140100          1081       36       73   1.116     141         56
1725     140100          1087       12       24   0.717     128         26
2254     140100          1088       10       39   0.800      99         19

      pm10_24h  Weekday  Month  Date  Year
2673       274        0     12     3  2016
747         52        0      4     3  2016
1033        81        1      5     9  2016
1705        57        1      8     1  2016
1408        44        0      6    25  2016
666        107        1      3    24  2016
2625       201        1     11    25  2016
633        243        0      3    20  2016
1709        56        1      8     1  2016
2489        70        1     11     7  2016
2314        46        0     10    16  2016
856         77        0      4    17  2016
1458        61        1      7     1  2016
2517       168        1     11    10  2016
166         76        1      1    12  2016
1176       101        1      5    27  2016
1443       133        1      6    29  2016
2294       227        1     10    13  2016
2235        97        1     10     6  2016
2174        61        1      9    28  2016
2592       111        1     11    21  2016
1173        81        1      5    26  2016
976        144        1      5     2  2016
433         68        0      2    27  2016
1902        38        1      8    25  2016
825         65        1      4    13  2016
2476       273        0     11     5  2016
1517        92        1      7     8  2016
120         94        1      1    28  2016
70         142        0      1     9  2016
...        ...      ...    ...   ...   ...
900        140        1      4    22  2016
2000        46        1      9     7  2016
2816       146        1     12    13  2016
2053        84        1      9    13  2016
974        215        0      5     1  2016
103         76        1      1    11  2016
2258        96        0     10     9  2016
1921        17        0      8    28  2016
1470        60        0      7     2  2016
41          66        1      1    11  2016
1386        68        1      6    22  2016
377        127        1      2    11  2016
1278       104        1      6     8  2016
2194        74        0     10     1  2016
2004        50        1      9     7  2016
205        129        1      1    20  2016
1068       106        1      5    13  2016
2075       142        1      9    16  2016
1461        92        1      7     1  2016
204         73        1      1    19  2016
2718       155        1     12     8  2016
2672       399        0     12     3  2016
2459       331        1     11     3  2016
1982        79        0      9     4  2016
740         88        0      4     2  2016
1032       143        1      5     9  2016
2121       176        1      9    22  2016
1424       116        1      6    27  2016
1725        64        1      8     3  2016
2254        74        0     10     8  2016

[2032 rows x 12 columns]

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=25, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [22]:
predictions = model.predict(test)
#predictionsArray = np.asarray(predictions, dtype="|S6")
#np.asarray(predictionsArray, dtype=np.float64) is predictionsArray
print(predictions)
print(test_df1.aqi)

[b'43.0' b'102.0' b'83.0' b'51.0' b'27.0' b'64.0' b'111.0' b'71.0' b'58.0'
 b'60.0' b'64.0' b'83.0' b'50.0' b'29.0' b'88.0' b'36.0' b'85.0' b'44.0'
 b'132.0' b'82.83' b'74.0' b'61.0' b'19.0' b'48.0' b'84.25' b'131.17'
 b'46.0' b'54.9' b'111.0' b'54.9' b'101.0' b'46.0' b'131.17' b'67.0'
 b'26.0' b'83.0' b'91.0' b'159.0' b'66.0' b'46.0' b'85.0' b'102.0' b'58.0'
 b'274.0' b'66.0' b'89.0' b'94.0' b'102.0' b'91.0' b'50.0' b'214.0'
 b'110.0' b'95.0' b'76.0' b'91.0' b'68.73' b'85.0' b'74.0' b'50.0' b'85.0'
 b'216.0' b'71.0' b'58.0' b'85.0' b'66.0' b'74.0' b'66.0' b'66.0' b'83.2'
 b'91.0' b'88.0' b'19.0' b'79.72' b'66.0' b'61.0' b'86.0' b'45.0' b'83.2'
 b'66.0' b'46.0' b'101.0' b'85.0' b'32.0' b'81.0' b'68.73' b'56.0' b'77.0'
 b'43.0' b'43.0' b'120.0' b'84.25' b'96.0' b'175.0' b'118.0' b'50.0'
 b'54.9' b'58.0' b'75.0' b'58.0' b'50.0' b'91.0' b'85.0' b'78.0' b'43.0'
 b'41.0' b'41.0' b'83.0' b'83.0' b'50.0' b'58.0' b'54.0' b'34.0' b'54.0'
 b'50.0' b'203.0' b'64.0' b'56.0' b'83.2' b'66.0' b'79.0' b'71.0' b'51.0'
 b'82.83' b'66.0' b'83.2' b'107.0' b'43.0' b'123.0' b'41.0' b'91.0' b'56.0'
 b'27.0' b'69.0' b'85.0' b'85.0' b'27.0' b'79.72' b'102.0' b'77.0'
 b'131.17' b'84.25' b'75.0' b'131.17' b'102.0' b'74.0' b'274.0' b'134.0'
 b'91.0' b'58.0' b'130.0' b'131.17' b'67.0' b'56.0' b'95.0' b'83.0' b'94.0'
 b'51.0' b'144.0' b'76.0' b'95.0' b'91.0' b'110.0' b'55.0' b'72.0' b'51.0'
 b'83.2' b'68.73' b'77.0' b'68.73' b'75.0' b'85.0' b'51.0' b'40.0' b'102.0'
 b'27.0' b'72.0' b'81.0' b'63.0' b'202.0' b'75.0' b'102.0' b'27.0' b'90.23'
 b'71.0' b'83.0' b'72.0' b'122.0' b'46.0' b'29.0' b'95.0' b'95.0' b'69.0'
 b'175.0' b'77.0' b'118.0' b'160.0' b'67.0' b'44.0' b'27.0' b'84.25'
 b'136.0' b'123.0' b'66.0' b'68.31' b'308.0' b'63.0' b'45.0' b'41.0'
 b'19.0' b'29.0' b'79.72' b'133.0' b'83.2' b'58.0' b'185.0' b'29.0' b'41.0'
 b'64.0' b'26.0' b'61.0' b'56.0' b'63.0' b'60.0' b'68.73' b'58.0' b'123.0'
 b'74.0' b'43.0' b'63.0' b'108.0' b'46.0' b'59.0' b'75.0' b'131.17' b'83.2'
 b'123.0' b'66.0' b'43.0' b'44.0' b'91.0' b'61.0' b'185.0' b'69.0' b'34.0'
 b'78.0' b'51.0' b'85.0' b'108.0' b'56.0' b'94.0' b'66.0' b'132.0' b'19.0'
 b'36.0' b'58.0' b'102.0' b'56.0' b'43.0' b'46.0' b'83.2' b'95.0' b'43.0'
 b'68.31' b'66.0' b'73.0' b'73.0' b'98.0' b'308.0' b'131.17' b'161.0'
 b'30.0' b'102.0' b'111.0' b'110.0' b'53.0' b'72.0' b'106.0' b'170.0'
 b'203.0' b'185.0' b'73.0' b'43.0' b'56.0' b'79.72' b'38.0' b'131.17'
 b'81.0' b'85.0' b'85.0' b'56.0' b'58.0' b'151.0' b'86.0' b'100.0' b'56.0'
 b'62.0' b'85.0' b'72.0' b'83.0' b'56.0' b'50.0' b'93.0' b'78.0' b'61.0'
 b'38.0' b'219.0' b'49.0' b'61.0' b'36.0' b'50.0' b'109.0' b'110.0' b'25.0'
 b'85.0' b'78.0' b'26.0' b'91.0' b'83.0' b'63.0' b'218.0' b'74.0' b'130.0'
 b'78.0' b'161.0' b'36.0' b'214.0' b'49.0' b'130.0' b'72.0' b'91.0'
 b'101.0' b'43.0' b'51.0' b'46.0' b'47.0' b'116.0' b'85.0' b'91.0' b'34.0'
 b'76.0' b'91.0' b'58.0' b'46.0' b'86.0' b'43.0' b'71.0' b'51.0' b'56.0'
 b'43.0' b'45.0' b'236.0' b'63.0' b'111.0' b'180.0' b'91.0' b'91.0' b'36.0'
 b'43.0' b'102.0' b'115.0' b'90.23' b'47.0' b'54.0' b'84.0' b'49.0'
 b'220.0' b'56.0' b'58.0' b'84.25' b'91.0' b'308.0' b'78.0' b'40.0'
 b'160.0' b'68.31' b'110.0' b'102.0' b'90.23' b'43.0' b'79.72' b'102.0'
 b'124.0' b'88.0' b'51.0' b'68.31' b'111.0' b'160.0' b'160.0' b'60.0'
 b'91.0' b'66.0' b'27.0' b'76.0' b'151.0' b'61.0' b'175.0' b'100.0'
 b'120.0' b'175.0' b'144.0' b'46.0' b'106.0' b'97.0' b'108.0' b'102.0'
 b'67.0' b'44.0' b'81.0' b'121.0' b'175.0' b'43.0' b'85.0' b'94.0' b'144.0'
 b'75.0' b'82.83' b'71.0' b'83.0' b'77.0' b'89.0' b'76.0' b'54.9' b'90.23'
 b'139.0' b'25.0' b'67.0' b'83.0' b'66.0' b'73.0' b'85.0' b'84.25' b'27.0'
 b'83.2' b'54.0' b'49.0' b'43.0' b'31.0' b'58.0' b'72.0' b'97.0' b'54.0'
 b'68.73' b'27.0' b'83.0' b'144.0' b'118.0' b'73.0' b'54.9' b'88.0'
 b'79.72' b'32.0' b'36.0' b'95.0' b'74.0' b'160.0' b'85.0' b'151.0' b'41.0'
 b'90.23' b'47.0' b'69.0' b'46.0' b'128.0' b'83.2' b'110.0' b'43.0'
 b'120.0' b'63.0' b'101.0' b'34.0' b'58.0' b'131.17' b'91.0' b'73.0'
 b'83.0' b'94.0' b'68.73' b'88.0' b'32.0' b'85.0' b'71.0' b'25.0' b'53.0'
 b'85.0' b'78.0' b'118.0' b'65.0' b'43.0' b'220.0' b'109.0' b'160.0'
 b'43.0' b'114.0' b'41.0' b'56.0' b'32.0' b'91.0' b'95.0' b'85.0' b'79.72'
 b'73.0' b'46.0' b'83.0' b'71.0' b'91.0' b'88.0' b'308.0' b'94.0' b'83.2'
 b'71.0' b'99.0' b'96.0' b'44.0' b'63.0' b'63.0' b'54.0' b'73.0' b'48.0'
 b'25.0' b'102.0' b'41.0' b'94.0' b'120.0' b'94.0' b'108.0' b'76.0' b'56.0'
 b'91.0' b'96.0' b'41.0' b'26.0' b'88.0' b'88.0' b'131.17' b'102.0' b'54.9'
 b'91.0' b'108.0' b'96.0' b'54.9' b'66.0' b'175.0' b'121.0' b'72.0' b'83.0'
 b'19.0' b'68.73' b'67.0' b'27.0' b'82.83' b'55.0' b'33.0' b'26.0' b'68.73'
 b'46.0' b'108.0' b'83.2' b'56.0' b'93.0' b'67.0' b'96.0' b'34.0' b'85.0'
 b'49.0' b'60.0' b'67.0' b'95.0' b'56.0' b'84.25' b'61.0' b'110.0' b'37.0'
 b'58.0' b'72.0' b'71.0' b'118.0' b'102.0' b'95.0' b'103.0' b'71.0' b'85.0'
 b'95.0' b'41.0' b'144.0' b'122.0' b'54.9' b'64.0' b'111.0' b'32.0'
 b'130.0' b'95.0' b'85.0' b'60.0' b'84.25' b'180.0' b'120.0' b'123.0'
 b'58.0' b'94.0' b'118.0' b'174.0' b'81.0' b'40.0' b'36.0' b'166.0'
 b'84.25' b'41.0' b'58.0' b'73.0' b'119.0' b'131.17' b'58.0' b'85.0'
 b'101.0' b'102.0' b'58.0' b'66.0' b'51.0' b'44.0' b'78.0' b'111.0'
 b'102.0' b'58.0' b'87.0' b'67.0' b'121.0' b'91.0' b'203.0' b'77.0'
 b'84.25' b'139.0' b'71.0' b'36.0' b'36.0' b'121.0' b'77.0' b'91.0' b'78.0'
 b'105.0' b'122.0' b'46.0' b'102.0' b'62.0' b'90.23' b'95.0' b'76.0'
 b'84.25' b'82.83' b'34.0' b'36.0' b'66.0' b'58.0' b'85.0' b'84.0' b'110.0'
 b'68.73' b'91.0' b'75.0' b'46.0' b'49.0' b'104.0' b'62.0' b'110.0'
 b'101.0' b'90.23' b'69.0' b'79.72' b'41.0' b'118.0' b'63.0' b'58.0'
 b'95.0' b'118.0' b'68.73' b'152.0' b'88.0' b'52.0' b'102.0' b'100.0'
 b'132.0' b'56.0' b'85.0' b'73.0' b'47.0' b'26.0' b'52.0' b'85.0' b'41.0'
 b'149.0' b'79.72' b'111.0' b'71.0' b'63.0' b'52.0' b'73.0' b'102.0'
 b'77.0' b'58.0' b'114.0' b'83.0' b'131.17' b'102.0' b'50.0' b'96.0'
 b'34.0' b'76.0' b'55.0' b'61.0' b'63.0' b'58.0' b'74.0' b'61.0' b'236.0'
 b'84.25' b'82.83' b'41.0' b'58.0' b'88.0' b'46.0' b'84.25' b'64.0'
 b'132.0' b'115.0' b'85.0' b'274.0' b'44.0' b'60.0' b'83.2' b'37.0' b'46.0'
 b'88.0' b'93.0' b'36.0' b'83.0' b'73.0' b'167.0' b'56.0' b'41.0' b'77.0'
 b'64.0' b'46.0' b'82.83' b'46.0' b'85.0' b'69.0' b'71.0' b'41.0' b'124.0'
 b'68.31' b'68.31' b'43.0' b'26.0' b'159.0' b'73.0' b'83.2' b'118.0'
 b'49.0' b'26.0' b'91.0' b'104.0' b'91.0' b'68.73' b'66.0' b'123.0' b'56.0'
 b'58.0' b'102.0' b'46.0' b'83.0' b'75.0' b'53.0' b'81.0' b'54.0' b'102.0'
 b'111.0' b'108.0' b'85.0' b'82.83' b'73.0' b'102.0' b'96.0' b'83.0'
 b'274.0' b'52.0' b'47.0' b'60.0' b'78.0' b'88.0' b'51.0' b'78.0' b'36.0'
 b'99.0' b'144.0' b'212.0' b'90.23' b'54.9' b'60.0' b'49.0' b'108.0'
 b'110.0' b'68.31' b'131.17' b'46.0' b'95.0' b'66.0' b'73.0' b'88.0'
 b'50.0' b'110.0' b'54.9' b'50.0' b'108.0' b'64.0' b'46.0' b'76.0' b'85.0'
 b'41.0' b'50.0' b'50.0' b'91.0' b'167.0' b'26.0' b'51.0' b'94.0' b'151.0'
 b'34.0' b'121.0' b'91.0' b'70.0' b'54.9' b'69.0' b'101.0' b'175.0'
 b'110.0' b'111.0' b'83.2' b'58.0' b'79.0' b'59.0' b'91.0' b'83.0' b'90.23'
 b'54.9' b'121.0' b'111.0' b'85.0' b'144.0' b'62.0' b'68.31' b'83.2'
 b'94.0' b'74.0' b'84.25' b'46.0' b'79.72' b'102.0' b'19.0' b'63.0' b'95.0'
 b'94.0' b'136.0' b'54.0' b'91.0' b'86.0' b'54.9' b'91.0' b'95.0' b'102.0'
 b'94.0' b'170.0' b'106.0' b'81.0']
0       40.00
1      100.00
2       79.00
3       50.00
4       32.00
5       65.00
6      109.00
7       76.00
8       57.00
9       69.00
10      63.00
11      82.00
12      53.00
13      23.00
14      89.00
15      35.00
16      80.00
17      41.00
18     142.00
19      68.31
20      75.00
21      61.00
22      22.00
23      49.00
24      82.83
25     152.00
26      46.00
27      79.72
28     111.00
29      82.83
        ...
842     68.31
843    127.00
844    116.00
845     73.00
846    133.00
847     70.00
848     68.31
849     90.23
850     93.00
851     71.00
852     83.20
853     43.00
854     79.72
855    104.00
856     17.00
857     68.00
858     94.00
859     89.00
860    155.00
861     47.00
862     91.00
863     88.00
864     54.90
865     93.00
866    108.00
867    102.00
868     92.00
869    160.00
870    118.00
871     80.00
Name: aqi, Length: 872, dtype: float64

In [23]:
newarray = np.asarray(test_df1['aqi'], dtype="|S8")
print(newarray)

[b'40.0' b'100.0' b'79.0' b'50.0' b'32.0' b'65.0' b'109.0' b'76.0' b'57.0'
 b'69.0' b'63.0' b'82.0' b'53.0' b'23.0' b'89.0' b'35.0' b'80.0' b'41.0'
 b'142.0' b'68.31' b'75.0' b'61.0' b'22.0' b'49.0' b'82.83' b'152.0'
 b'46.0' b'79.72' b'111.0' b'82.83' b'100.0' b'40.0' b'136.0' b'68.0'
 b'21.0' b'84.0' b'84.0' b'140.0' b'78.0' b'47.0' b'91.0' b'108.0' b'61.0'
 b'286.0' b'65.0' b'91.0' b'106.0' b'113.0' b'91.0' b'44.0' b'253.0'
 b'121.0' b'100.0' b'71.0' b'95.0' b'68.73' b'77.0' b'77.0' b'55.0' b'81.0'
 b'178.0' b'67.0' b'63.0' b'86.0' b'75.0' b'71.0' b'71.0' b'63.0' b'83.2'
 b'89.0' b'86.0' b'23.0' b'235.0' b'71.0' b'63.0' b'82.0' b'46.0' b'54.9'
 b'67.0' b'47.0' b'124.0' b'88.0' b'29.0' b'80.0' b'68.73' b'53.0' b'117.0'
 b'42.0' b'44.0' b'135.0' b'84.25' b'97.0' b'181.0' b'143.0' b'51.0'
 b'54.9' b'62.0' b'75.0' b'56.0' b'48.0' b'88.0' b'83.0' b'77.0' b'43.0'
 b'38.0' b'40.0' b'86.0' b'87.0' b'53.0' b'59.0' b'50.0' b'33.0' b'60.0'
 b'51.0' b'207.0' b'65.0' b'58.0' b'54.9' b'63.0' b'78.0' b'72.0' b'50.0'
 b'68.73' b'70.0' b'68.31' b'117.0' b'41.0' b'126.0' b'38.0' b'90.0'
 b'63.0' b'25.0' b'69.0' b'90.0' b'81.0' b'25.0' b'202.0' b'103.0' b'79.0'
 b'125.0' b'54.9' b'80.0' b'131.17' b'103.0' b'75.0' b'293.0' b'136.0'
 b'95.0' b'56.0' b'112.0' b'277.0' b'70.0' b'56.0' b'97.0' b'100.0' b'93.0'
 b'51.0' b'138.0' b'81.0' b'95.0' b'92.0' b'172.0' b'59.0' b'75.0' b'56.0'
 b'54.9' b'68.73' b'83.0' b'68.73' b'79.0' b'78.0' b'55.0' b'39.0' b'102.0'
 b'28.0' b'81.0' b'81.0' b'62.0' b'251.0' b'69.0' b'101.0' b'29.0' b'90.23'
 b'74.0' b'89.0' b'76.0' b'121.0' b'44.0' b'26.0' b'93.0' b'101.0' b'62.0'
 b'175.0' b'78.0' b'119.0' b'167.0' b'65.0' b'42.0' b'27.0' b'84.25'
 b'145.0' b'136.0' b'66.0' b'82.83' b'286.0' b'74.0' b'46.0' b'38.0'
 b'19.0' b'30.0' b'184.0' b'140.0' b'83.2' b'56.0' b'182.0' b'30.0' b'41.0'
 b'65.0' b'27.0' b'62.0' b'37.0' b'57.0' b'65.0' b'82.83' b'58.0' b'137.0'
 b'68.0' b'41.0' b'47.0' b'115.0' b'44.0' b'60.0' b'78.0' b'131.17'
 b'288.0' b'129.0' b'66.0' b'41.0' b'40.0' b'98.0' b'62.0' b'185.0' b'66.0'
 b'33.0' b'81.0' b'51.0' b'82.0' b'103.0' b'61.0' b'95.0' b'66.0' b'135.0'
 b'21.0' b'39.0' b'51.0' b'108.0' b'56.0' b'44.0' b'45.0' b'68.73' b'90.0'
 b'42.0' b'68.31' b'69.0' b'71.0' b'75.0' b'112.0' b'322.0' b'132.0'
 b'140.0' b'23.0' b'131.17' b'113.0' b'107.0' b'56.0' b'75.0' b'112.0'
 b'170.0' b'255.0' b'171.0' b'77.0' b'45.0' b'57.0' b'210.0' b'37.0'
 b'127.0' b'111.0' b'76.0' b'82.0' b'57.0' b'55.0' b'152.0' b'87.0'
 b'113.0' b'60.0' b'77.0' b'100.0' b'70.0' b'119.0' b'58.0' b'53.0' b'92.0'
 b'75.0' b'64.0' b'38.0' b'252.0' b'53.0' b'78.0' b'35.0' b'55.0' b'112.0'
 b'120.0' b'24.0' b'83.0' b'84.0' b'30.0' b'88.0' b'82.0' b'71.0' b'270.0'
 b'76.0' b'125.0' b'84.0' b'159.0' b'38.0' b'210.0' b'49.0' b'180.0'
 b'77.0' b'99.0' b'115.0' b'42.0' b'54.0' b'43.0' b'43.0' b'129.0' b'86.0'
 b'93.0' b'32.0' b'77.0' b'94.0' b'61.0' b'48.0' b'86.0' b'42.0' b'75.0'
 b'49.0' b'55.0' b'38.0' b'44.0' b'272.0' b'62.0' b'122.0' b'207.0' b'96.0'
 b'92.0' b'37.0' b'45.0' b'116.0' b'110.0' b'90.23' b'47.0' b'55.0' b'82.0'
 b'46.0' b'221.0' b'60.0' b'55.0' b'82.83' b'131.17' b'288.0' b'76.0'
 b'38.0' b'169.0' b'68.31' b'187.0' b'99.0' b'126.0' b'40.0' b'79.72'
 b'116.0' b'120.0' b'88.0' b'53.0' b'82.83' b'116.0' b'163.0' b'172.0'
 b'57.0' b'99.0' b'66.0' b'24.0' b'82.0' b'148.0' b'59.0' b'187.0' b'110.0'
 b'128.0' b'192.0' b'145.0' b'46.0' b'114.0' b'100.0' b'103.0' b'100.0'
 b'65.0' b'42.0' b'73.0' b'150.0' b'191.0' b'45.0' b'93.0' b'101.0'
 b'140.0' b'79.0' b'68.73' b'69.0' b'80.0' b'77.0' b'98.0' b'76.0' b'54.9'
 b'90.23' b'128.0' b'28.0' b'68.0' b'105.0' b'67.0' b'74.0' b'76.0'
 b'84.25' b'18.0' b'68.31' b'55.0' b'50.0' b'47.0' b'26.0' b'64.0' b'68.0'
 b'99.0' b'52.0' b'68.73' b'24.0' b'80.0' b'146.0' b'118.0' b'74.0'
 b'68.73' b'92.0' b'79.72' b'31.0' b'41.0' b'98.0' b'71.0' b'171.0' b'86.0'
 b'134.0' b'40.0' b'358.0' b'47.0' b'67.0' b'43.0' b'133.0' b'79.72'
 b'110.0' b'42.0' b'127.0' b'62.0' b'115.0' b'33.0' b'54.0' b'124.0'
 b'99.0' b'70.0' b'85.0' b'91.0' b'68.73' b'85.0' b'29.0' b'79.0' b'74.0'
 b'22.0' b'52.0' b'79.0' b'76.0' b'121.0' b'69.0' b'40.0' b'214.0' b'116.0'
 b'163.0' b'37.0' b'105.0' b'43.0' b'47.0' b'30.0' b'102.0' b'89.0' b'88.0'
 b'79.72' b'84.0' b'47.0' b'109.0' b'76.0' b'94.0' b'85.0' b'329.0' b'94.0'
 b'83.2' b'66.0' b'99.0' b'94.0' b'38.0' b'66.0' b'64.0' b'55.0' b'75.0'
 b'46.0' b'25.0' b'118.0' b'36.0' b'92.0' b'152.0' b'92.0' b'109.0' b'73.0'
 b'55.0' b'104.0' b'102.0' b'38.0' b'27.0' b'98.0' b'88.0' b'104.0'
 b'126.0' b'79.72' b'95.0' b'115.0' b'97.0' b'54.9' b'66.0' b'187.0'
 b'120.0' b'70.0' b'89.0' b'21.0' b'83.2' b'67.0' b'22.0' b'82.83' b'53.0'
 b'30.0' b'31.0' b'83.2' b'46.0' b'106.0' b'83.2' b'57.0' b'100.0' b'71.0'
 b'108.0' b'35.0' b'90.0' b'50.0' b'61.0' b'70.0' b'98.0' b'54.0' b'82.83'
 b'61.0' b'116.0' b'36.0' b'58.0' b'72.0' b'76.0' b'119.0' b'123.0' b'95.0'
 b'100.0' b'81.0' b'85.0' b'95.0' b'36.0' b'140.0' b'117.0' b'68.73'
 b'64.0' b'104.0' b'32.0' b'120.0' b'96.0' b'78.0' b'59.0' b'84.25'
 b'181.0' b'135.0' b'129.0' b'55.0' b'92.0' b'117.0' b'195.0' b'106.0'
 b'45.0' b'36.0' b'163.0' b'84.25' b'43.0' b'58.0' b'69.0' b'121.0'
 b'131.17' b'57.0' b'83.0' b'102.0' b'109.0' b'61.0' b'67.0' b'49.0'
 b'38.0' b'77.0' b'112.0' b'126.0' b'56.0' b'87.0' b'73.0' b'122.0'
 b'107.0' b'216.0' b'78.0' b'84.25' b'146.0' b'73.0' b'38.0' b'37.0'
 b'118.0' b'85.0' b'101.0' b'79.0' b'112.0' b'158.0' b'42.0' b'108.0'
 b'59.0' b'122.0' b'100.0' b'74.0' b'84.25' b'82.83' b'35.0' b'39.0'
 b'66.0' b'62.0' b'84.0' b'100.0' b'125.0' b'83.2' b'96.0' b'73.0' b'45.0'
 b'51.0' b'108.0' b'69.0' b'118.0' b'104.0' b'219.0' b'73.0' b'79.72'
 b'35.0' b'114.0' b'60.0' b'57.0' b'95.0' b'117.0' b'82.83' b'132.0'
 b'90.0' b'54.0' b'109.0' b'97.0' b'130.0' b'53.0' b'79.0' b'71.0' b'43.0'
 b'27.0' b'53.0' b'86.0' b'37.0' b'153.0' b'54.9' b'112.0' b'73.0' b'76.0'
 b'60.0' b'69.0' b'115.0' b'77.0' b'59.0' b'127.0' b'87.0' b'111.0'
 b'106.0' b'52.0' b'98.0' b'33.0' b'74.0' b'56.0' b'52.0' b'61.0' b'58.0'
 b'74.0' b'62.0' b'251.0' b'84.25' b'82.83' b'43.0' b'59.0' b'112.0'
 b'45.0' b'84.25' b'67.0' b'120.0' b'124.0' b'88.0' b'307.0' b'43.0'
 b'61.0' b'83.2' b'36.0' b'44.0' b'86.0' b'88.0' b'41.0' b'80.0' b'75.0'
 b'184.0' b'56.0' b'38.0' b'76.0' b'67.0' b'45.0' b'68.73' b'47.0' b'85.0'
 b'69.0' b'79.0' b'38.0' b'151.0' b'68.31' b'68.31' b'40.0' b'22.0'
 b'139.0' b'72.0' b'82.83' b'117.0' b'47.0' b'25.0' b'86.0' b'107.0'
 b'98.0' b'68.73' b'68.0' b'134.0' b'58.0' b'55.0' b'115.0' b'49.0' b'83.0'
 b'79.0' b'55.0' b'78.0' b'54.0' b'134.0' b'117.0' b'147.0' b'82.0'
 b'68.31' b'70.0' b'116.0' b'98.0' b'82.0' b'326.0' b'54.0' b'38.0' b'59.0'
 b'76.0' b'86.0' b'54.0' b'77.0' b'38.0' b'109.0' b'139.0' b'239.0'
 b'90.23' b'54.9' b'59.0' b'45.0' b'110.0' b'116.0' b'68.31' b'199.0'
 b'48.0' b'94.0' b'71.0' b'69.0' b'94.0' b'47.0' b'113.0' b'54.9' b'46.0'
 b'110.0' b'63.0' b'45.0' b'79.0' b'85.0' b'41.0' b'51.0' b'48.0' b'89.0'
 b'131.0' b'20.0' b'52.0' b'93.0' b'136.0' b'32.0' b'126.0' b'159.0'
 b'67.0' b'68.31' b'72.0' b'116.0' b'157.0' b'104.0' b'113.0' b'83.2'
 b'55.0' b'85.0' b'57.0' b'92.0' b'83.0' b'90.23' b'68.31' b'127.0'
 b'116.0' b'73.0' b'133.0' b'70.0' b'68.31' b'90.23' b'93.0' b'71.0'
 b'83.2' b'43.0' b'79.72' b'104.0' b'17.0' b'68.0' b'94.0' b'89.0' b'155.0'
 b'47.0' b'91.0' b'88.0' b'54.9' b'93.0' b'108.0' b'102.0' b'92.0' b'160.0'
 b'118.0' b'80.0']

In [24]:
# Print accuracy
accuracy = metrics.accuracy_score(predictions, newarray,  normalize=True)
print("Accuracy over Testing Data: %s" % "{0:.3%}".format(accuracy))

Accuracy over Testing Data: 13.647%

In [25]:
#predict_rfc =rfc.predict(test)
from sklearn.metrics import f1_score
f1_score(newarray, predictions, average='micro')

0.13646788990825687

In [26]:
c=0
import math
predictionsArr = np.asarray(predictions, dtype="|f8")
realArr = np.asarray(newarray, dtype="|f8")

for x in range(0,len(predictionsArr)):
    c += math.fabs((predictionsArr[x]-realArr[x]))
print(100 - c/len(predictions))
c=0
for x in range(0,len(predictionsArr)):
    c += (math.fabs((predictionsArr[x]-realArr[x]))/realArr[x])*100
print(100 - c/len(predictions))

92.78911697247706
93.0297631354